# Generated by Django 4.1.2 on 2022-11-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('in progress', 'in progress'), ('done', 'done'), ('delayed', 'delayed'), ('queued', 'queued'), ('under review', 'under review'), ('accepted', 'accepted'), ('refused', 'refused'), ('closed', 'closed')], default='under review', max_length=50)),
                ('report', models.TextField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='dashboard.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('done', 'done'), ('delayed', 'delayed'), ('queued', 'queued'), ('under review', 'under review'), ('accepted', 'accepted'), ('refused', 'refused'), ('closed', 'closed')], default='queued', max_length=50),
        ),
    ]
