# Generated by Django 4.1.2 on 2022-11-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_employeerequests_task_description_task_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequests',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('done', 'done'), ('delayed', 'delayed'), ('queued', 'queued'), ('under review', 'under review'), ('accepted', 'accepted'), ('refused', 'refused'), ('closed', 'closed'), ('solved', 'solved')], default='under review', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('done', 'done'), ('delayed', 'delayed'), ('queued', 'queued'), ('under review', 'under review'), ('accepted', 'accepted'), ('refused', 'refused'), ('closed', 'closed'), ('solved', 'solved')], default='queued', max_length=50),
        ),
        migrations.CreateModel(
            name='BugTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('in progress', 'in progress'), ('done', 'done'), ('delayed', 'delayed'), ('queued', 'queued'), ('under review', 'under review'), ('accepted', 'accepted'), ('refused', 'refused'), ('closed', 'closed'), ('solved', 'solved')], default='under review', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
            ],
        ),
    ]
