# Generated by Django 4.1.2 on 2022-11-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_employeerequests_status_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='step',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
