# Generated by Django 4.1.2 on 2022-11-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_task_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tasks',
        ),
    ]
