# Generated by Django 4.1.2 on 2022-11-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_team_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='dashboard.task'),
        ),
    ]
