# Generated by Django 4.1.2 on 2022-11-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_task'),
        ('dashboard', '0006_team_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='colleagues',
            field=models.ManyToManyField(blank=True, related_name='colleagues', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='department',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='dashboard.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
