# Generated by Django 4.1.2 on 2022-11-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_report_remove_task_step_task_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='step',
            new_name='issuetype',
        ),
    ]
