# Generated by Django 4.1.2 on 2022-11-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_step_report_issuetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='issuetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
