# Generated by Django 4.1.2 on 2022-11-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_bugtracker_name_remove_employeerequests_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtracker',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeerequests',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('done', 'done'), ('delayed', 'delayed'), ('queued', 'queued'), ('under review', 'under review'), ('accepted', 'accepted'), ('refused', 'refused'), ('closed', 'closed'), ('solved', 'solved')], default='queued', max_length=50),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('done', 'done'), ('delayed', 'delayed'), ('queued', 'queued'), ('under review', 'under review'), ('accepted', 'accepted'), ('refused', 'refused'), ('closed', 'closed'), ('solved', 'solved')], default='queued', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeerequests',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('done', 'done'), ('delayed', 'delayed'), ('queued', 'queued'), ('under review', 'under review'), ('accepted', 'accepted'), ('refused', 'refused'), ('closed', 'closed'), ('solved', 'solved')], default='queued', max_length=50),
        ),
    ]
