# Generated by Django 4.1.2 on 2022-11-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_bugtracker_is_read_employeerequests_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtracker',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('done', 'done'), ('delayed', 'delayed'), ('queued', 'queued'), ('under review', 'under review'), ('accepted', 'accepted'), ('refused', 'refused'), ('open', 'open'), ('closed', 'closed'), ('solved', 'solved')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeerequests',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('done', 'done'), ('delayed', 'delayed'), ('queued', 'queued'), ('under review', 'under review'), ('accepted', 'accepted'), ('refused', 'refused'), ('open', 'open'), ('closed', 'closed'), ('solved', 'solved')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('done', 'done'), ('delayed', 'delayed'), ('queued', 'queued'), ('under review', 'under review'), ('accepted', 'accepted'), ('refused', 'refused'), ('open', 'open'), ('closed', 'closed'), ('solved', 'solved')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('done', 'done'), ('delayed', 'delayed'), ('queued', 'queued'), ('under review', 'under review'), ('accepted', 'accepted'), ('refused', 'refused'), ('open', 'open'), ('closed', 'closed'), ('solved', 'solved')], default='queued', max_length=50),
        ),
    ]
