# Generated by Django 4.1.2 on 2022-11-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_bugtracker_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugtracker',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='employeerequests',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_read',
        ),
    ]
