# Generated by Django 4.1.2 on 2022-11-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_bugtracker_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='report',
        ),
    ]
