# Generated by Django 4.1.2 on 2022-11-02 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_task_step'),
        ('accounts', '0003_rename_language_profile_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.task'),
        ),
    ]
