# Generated by Django 4.1.2 on 2022-11-03 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_report_remove_task_step_task_report'),
        ('accounts', '0005_remove_profile_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department'),
        ),
    ]
